In [1]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

C = A + B

print("Matrix A:")
print(A)

print("Matrix B:")
print(B)

print("Sum of matrices:")
print(C)


Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
Sum of matrices:
[[ 6  8]
 [10 12]]
