In [5]:
#numpy slicing

import numpy as x
y=x.array([[1,2,3,4,5],[6,7,8,9,0]])
print(y[0,1:4])

[2 3 4]


In [6]:
import numpy as x
y=x.array([[1,2,3,4,5],[6,7,8,9,0]])
print(y[0,:3])

[1 2 3]


In [7]:
import numpy as x
y=x.array([[1,2,3,4,5],[6,7,8,9,0]])
print(y[1,:3])

[6 7 8]


In [9]:
import numpy as x
y=x.array([[1,2,3,4,5],[6,7,8,9,0]])
print(y[0,3:])

[4 5]


In [11]:
import numpy as x
y=x.array([[1,2,3,4,5],[6,7,8,9,0]])
print(y[1,3:])

[9 0]


In [23]:
import numpy as x
y=x.array([[1,2,3,4,5],[6,7,8,9,0]])
z=y[1,2]
print(z)

8


In [22]:
import numpy as x
y=x.array([[1,2,3,4,5],[6,7,8,9,0],[10,11,12,13,14]])
z=y[:,1:3]
print(z)

[[ 2  3]
 [ 7  8]
 [11 12]]
